const ACTIONS = {
    LIST:"LIST",
    FAILED:"FAILED",
    CLEAR_ALL_ITEMS:"CLEAR_ALL_ITEMS",
    ADD_ITEMS:"ADD_ITEMS",
    DELETE_ITEM:"DELETE_ITEM",
    UPDATE_CHECKBOX:"UPDATE_CHECKBOX",
    UPDATE_SEARCH_INPUT:"UPDATE_SEARCH_INPUT",
    GET_SORT:"GET_SORT",
    UPDATE_DATE:"UPDATE_DATE"
};

export default ACTIONS;
